all:
	cd 'Task 2.1A' && make 
	cd 'Task 2.1B' && make 
	cd 'Task 2.1C' && make 
	cd 'Task 2.2A' && make 
	cd 'Task 2.2B' && make 
	cd 'Task 2.3' && make 

	
.PHONY: clean all
clean:
	cd 'Task 2.1A' && make clean
	cd 'Task 2.1B' && make clean
	cd 'Task 2.1C' && make clean
	cd 'Task 2.2A' && make clean
	cd 'Task 2.2B' && make clean
	cd 'Task 2.3' && make clean
